name: geopandas_docs
channels:
  - conda-forge
dependencies:
  - python=3.8  
  - shapely
  - pyproj
  - scikit-learn
  - geopy
  - matplotlib
  - mapclassify
  - numpydoc
  - ipython
  - pillow
  - mock
  - cartopy
  - pyepsg
  - rasterio
  - geoplot
  - dask
  - dask-image
  - dask-ml
  - dask-labextension
  - gdal
  - libgdal
  - proj
  - geos
  - jupyter_client
  - ipykernel
  - libpysal
  - pygeos
  - pip
  - pip:
          - jupyter-book
          - geopandas
          - rasterio
          - pandas
          - numpy
          - geemap
          - merf
          - statsmodels  
          - sat-search
          - pytest
