name: geopandas_docs
channels:
  - conda-forge
dependencies:
  - python=3.8  
  - shapely
  - fiona
  - pyproj
  - rtree
  - geopy
  - matplotlib
  - mapclassify
  - numpydoc
  - ipython
  - pillow
  - mock
  - cartopy
  - pyepsg
  - rasterio
  - geoplot
  - dask
  - dask-image
  - dask-ml
  - dask-labextension
  - jupytext
  - gdal
  - libgdal
  - proj
  - geos
  - jupyter_client
  - ipykernel
  - folium
  - libpysal
  - pygeos
  - xarray
  - holoviews
  - earthengine-api
  - pip
  - pip:
          - jupyter-book
          - geopandas
          - rasterio
          - pandas
          - numpy
          - geemap
          - merf
          - statsmodels  
          - sat-search
